language: node_js
node_js:
  - "11.3.0"
cache: npm

script:
  - mkdir out
  - cp index.html out/index.html
  - ./intro-to-reasonml/build.sh
  - ./intro-to-reason-react/build.sh

deploy:
  local-dir: out
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  fqdn: talks.anis.com.au
  on:
    branch: master
